#!/usr/bin/env python3
"""Generate or check the private Supabase word seed."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

from check_word_pack import load_development_seed_words, require


ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "supabase/seed.sql"
DEVELOPMENT_PACK_REL = Path("shared/word-packs/development-en-US-v1.json")


def seed_bytes(words: list[str], pack_version: int) -> bytes:
    rows = ",\n".join(
        f"  ('{word}', true, true, true, {pack_version})" for word in words
    )
    sql = f"""-- Generated by scripts/generate_supabase_seed.py from {DEVELOPMENT_PACK_REL}.
-- Do not edit by hand.

insert into private.words (
  word,
  is_accepted,
  is_answer,
  is_active,
  pack_version
)
values
{rows}
on conflict (word) do update set
  is_accepted = excluded.is_accepted,
  is_answer = excluded.is_answer,
  is_active = excluded.is_active,
  pack_version = excluded.pack_version;
"""
    return sql.encode()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="replace supabase/seed.sql with the deterministic value",
    )
    args = parser.parse_args()

    try:
        words, pack_version = load_development_seed_words()
        expected = seed_bytes(words, pack_version)
        if args.write:
            SEED.write_bytes(expected)
        else:
            require(
                SEED.read_bytes() == expected,
                "seed is stale; run with --write",
            )
    except (OSError, UnicodeError, ValueError) as error:
        print(f"Supabase seed check failed: {error}", file=sys.stderr)
        return 1

    print(f"Supabase seed check passed: {len(words)} words")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
